export const content = {
  es: {
    nombre: 'Yanina',
    apodo: 'Yani',
    titulo: 'Psicóloga · Paraná, Entre Ríos 🇦🇷',
    frase: 'Un espacio para escucharte, comprenderte y trabajar en aquello que hoy necesitás.',
    bio: 'Acompaño procesos de crecimiento personal y bienestar emocional desde una mirada empática, humana y respetuosa.',
    cita: 'Tu bienestar también merece ser una prioridad.',
    navCta: 'Agendar consulta',
    heroBtn: 'Reservar primera sesión',
    especialidadesTitulo: 'Cómo puedo ayudarte',
    especialidades: [
      { titulo: 'Salud mental y bienestar emocional', desc: 'Acompañamiento en procesos de ansiedad, estrés y malestar emocional.' },
      { titulo: 'Atención personalizada', desc: 'Un espacio pensado para vos, a tu ritmo y sin juicios.' },
      { titulo: 'Crecimiento personal', desc: 'Herramientas para el autoconocimiento y la toma de decisiones.' },
    ],
    agendaTitulo: '¿Lista para dar el primer paso?',
    agendaTexto: 'Las sesiones son por videollamada, con horarios flexibles. Elegí el mejor día para vos.',
    agendaBtn: 'Ver horarios disponibles',
    ubicacion: 'Paraná, Entre Ríos',
  },
  pt: {
    nombre: 'Yanina',
    apodo: 'Yani',
    titulo: 'Psicóloga · Paraná, Entre Ríos 🇦🇷',
    frase: 'Um espaço para te ouvir, te compreender e trabalhar naquilo que você precisa hoje.',
    bio: 'Acompanho processos de crescimento pessoal e bem-estar emocional com um olhar empático, humano e respeitoso.',
    cita: 'O seu bem-estar também merece ser prioridade.',
    navCta: 'Agendar consulta',
    heroBtn: 'Marcar primeira sessão',
    especialidadesTitulo: 'Como posso te ajudar',
    especialidades: [
      { titulo: 'Saúde mental e bem-estar emocional', desc: 'Acompanhamento em processos de ansiedade, estresse e mal-estar emocional.' },
      { titulo: 'Atendimento personalizado', desc: 'Um espaço pensado para você, no seu ritmo e sem julgamentos.' },
      { titulo: 'Crescimento pessoal', desc: 'Ferramentas para o autoconhecimento e a tomada de decisões.' },
    ],
    agendaTitulo: 'Pronta para dar o primeiro passo?',
    agendaTexto: 'As sessões são por videochamada, com horários flexíveis. Escolha o melhor dia para você.',
    agendaBtn: 'Ver horários disponíveis',
    ubicacion: 'Paraná, Entre Ríos',
  },
}
