export const content = {
  es: {
    nombre: 'Yanina',
    apodo: 'Yani',
    titulo: 'Psicóloga · Paraná, Entre Ríos 🇦🇷',
    frase: 'Un espacio para escucharte, comprenderte y trabajar en aquello que hoy necesitás.',
    bio: 'Acompaño procesos de crecimiento personal y bienestar emocional desde una mirada empática, humana y respetuosa.',
    cita: 'Tu bienestar también merece ser una prioridad.',
    navCta: 'Agendar consulta',
    heroBtn: 'Reservar primera sesión',
    especialidadesTitulo: 'Cómo puedo ayudarte',
    especialidades: [
      { titulo: 'Salud mental y bienestar emocional', desc: 'Acompañamiento en procesos de ansiedad, estrés y malestar emocional.' },
      { titulo: 'Atención personalizada', desc: 'Un espacio pensado para vos, a tu ritmo y sin juicios.' },
      { titulo: 'Crecimiento personal', desc: 'Herramientas para el autoconocimiento y la toma de decisiones.' },
    ],
    agendaTitulo: '¿Lista para dar el primer paso?',
    agendaTexto: 'Las sesiones son por videollamada, con horarios flexibles. Elegí el mejor día para vos.',
    agendaBtn: 'Ver horarios disponibles',
    ubicacion: 'Paraná, Entre Ríos',

    // Auth
    loginTitulo: 'Iniciar sesión',
    loginSubtitulo: 'Accedé para ver tus consultas y pagos.',
    cadastroTitulo: 'Crear cuenta',
    cadastroSubtitulo: 'Registrate para poder agendar tu sesión.',
    campoNombre: 'Nombre completo',
    campoTelefone: 'Teléfono',
    campoEmail: 'Correo electrónico',
    campoSenha: 'Contraseña',
    botaoEntrar: 'Entrar',
    botaoCrearCuenta: 'Crear cuenta',
    linkParaCadastro: '¿No tenés cuenta? Registrate',
    linkParaLogin: '¿Ya tenés cuenta? Iniciar sesión',
    erroGenerico: 'Algo salió mal. Intentá de nuevo.',

    // Agendar
    agendarTitulo: 'Elegí el día y horario',
    agendarSubtitulo: 'Sesiones online, de 50 minutos.',
    semHorarios: 'No hay horarios disponibles esta semana.',
    horarioReservado: 'Horario reservado',
    confirmarAgendamento: 'Confirmar y pagar',
    precisaLogin: 'Necesitás iniciar sesión para agendar una consulta.',

    // Admin
    adminLoginSubtitulo: 'Acceso solo para la administradora.',
    semAcesso: 'Esta cuenta no tiene permisos de administradora.',
    adminTabPerfil: 'Perfil',
    adminTabHorarios: 'Horarios',
    adminTabAgendamentos: 'Consultas',
    campoFrase: 'Frase principal',
    campoBio: 'Biografía',
    campoCita: 'Cita destacada',
    campoInstagram: 'Instagram',
    campoFotoUrl: 'URL de la foto',
    botaoSalvar: 'Guardar cambios',
    guardadoOk: 'Cambios guardados.',
    diaSemanaLabel: 'Día de la semana',
    horaLabel: 'Hora',
    botaoAdicionar: 'Agregar horario',
    horariosVazio: 'Todavía no hay horarios configurados.',
    botaoRemover: 'Quitar',
    agendamentosVazio: 'Todavía no hay consultas agendadas.',
    colunaData: 'Fecha',
    colunaCliente: 'Cliente',
    colunaStatus: 'Estado',
    pagoOkMsg: '¡Pago aprobado! Tu consulta está confirmada.',
    pagoErroMsg: 'El pago no se completó. Podés intentar de nuevo.',
    pagoPendenteMsg: 'Tu pago está pendiente de confirmación.',
    campoPrecio: 'Precio de la consulta (ARS)',
  },
  pt: {
    nombre: 'Yanina',
    apodo: 'Yani',
    titulo: 'Psicóloga · Paraná, Entre Ríos 🇦🇷',
    frase: 'Um espaço para te ouvir, te compreender e trabalhar naquilo que você precisa hoje.',
    bio: 'Acompanho processos de crescimento pessoal e bem-estar emocional com um olhar empático, humano e respeitoso.',
    cita: 'O seu bem-estar também merece ser prioridade.',
    navCta: 'Agendar consulta',
    heroBtn: 'Marcar primeira sessão',
    especialidadesTitulo: 'Como posso te ajudar',
    especialidades: [
      { titulo: 'Saúde mental e bem-estar emocional', desc: 'Acompanhamento em processos de ansiedade, estresse e mal-estar emocional.' },
      { titulo: 'Atendimento personalizado', desc: 'Um espaço pensado para você, no seu ritmo e sem julgamentos.' },
      { titulo: 'Crescimento pessoal', desc: 'Ferramentas para o autoconhecimento e a tomada de decisões.' },
    ],
    agendaTitulo: 'Pronta para dar o primeiro passo?',
    agendaTexto: 'As sessões são por videochamada, com horários flexíveis. Escolha o melhor dia para você.',
    agendaBtn: 'Ver horários disponíveis',
    ubicacion: 'Paraná, Entre Ríos',

    // Auth
    loginTitulo: 'Entrar',
    loginSubtitulo: 'Acesse para ver suas consultas e pagamentos.',
    cadastroTitulo: 'Criar conta',
    cadastroSubtitulo: 'Cadastre-se para poder agendar sua sessão.',
    campoNombre: 'Nome completo',
    campoTelefone: 'Telefone',
    campoEmail: 'E-mail',
    campoSenha: 'Senha',
    botaoEntrar: 'Entrar',
    botaoCrearCuenta: 'Criar conta',
    linkParaCadastro: 'Não tem conta? Cadastre-se',
    linkParaLogin: 'Já tem conta? Entrar',
    erroGenerico: 'Algo deu errado. Tente novamente.',

    // Agendar
    agendarTitulo: 'Escolha o dia e horário',
    agendarSubtitulo: 'Sessões online, de 50 minutos.',
    semHorarios: 'Não há horários disponíveis esta semana.',
    horarioReservado: 'Horário reservado',
    confirmarAgendamento: 'Confirmar e pagar',
    precisaLogin: 'Você precisa entrar para agendar uma consulta.',

    // Admin
    adminLoginSubtitulo: 'Acesso apenas para a administradora.',
    semAcesso: 'Esta conta não tem permissão de administradora.',
    adminTabPerfil: 'Perfil',
    adminTabHorarios: 'Horários',
    adminTabAgendamentos: 'Consultas',
    campoFrase: 'Frase principal',
    campoBio: 'Biografia',
    campoCita: 'Citação em destaque',
    campoInstagram: 'Instagram',
    campoFotoUrl: 'URL da foto',
    botaoSalvar: 'Salvar alterações',
    guardadoOk: 'Alterações salvas.',
    diaSemanaLabel: 'Dia da semana',
    horaLabel: 'Hora',
    botaoAdicionar: 'Adicionar horário',
    horariosVazio: 'Ainda não há horários configurados.',
    botaoRemover: 'Remover',
    agendamentosVazio: 'Ainda não há consultas agendadas.',
    colunaData: 'Data',
    colunaCliente: 'Cliente',
    colunaStatus: 'Status',
    pagoOkMsg: 'Pagamento aprovado! Sua consulta está confirmada.',
    pagoErroMsg: 'O pagamento não foi concluído. Você pode tentar de novo.',
    pagoPendenteMsg: 'Seu pagamento está pendente de confirmação.',
    campoPrecio: 'Preço da consulta (ARS)',
  },
}
