export const ui = {
  es: {
    about: "Sobre mí",
    approach: "Mi acompañamiento",
    how: "Cómo funciona",
    account: "Mis consultas",
    logout: "Salir",
    eyebrow: "PSICOLOGÍA · UN ESPACIO PARA VOS",
    heroTitle: "Volver a vos,",
    heroEm: "a tu propio ritmo.",
    heroNote: "Un primer paso, sin tener que resolverlo todo hoy.",
    online: "Atención online",
    duration: "Sesiones de 50 minutos",
    language: "Español y portugués",
    meet: "UN ENCUENTRO CON VOS",
    approachTitle: "No tenés que transitarlo",
    approachEm: "en soledad.",
    aboutLabel: "HOLA, SOY",
    aboutTitle: "Escuchar también es",
    aboutEm: "una forma de cuidar.",
    howLabel: "PASO A PASO, A TU RITMO",
    howTitle: "Empezar puede ser sencillo.",
    steps: [
      [
        "Elegí un momento",
        "Consultá los horarios y encontrá un espacio en tu semana.",
      ],
      [
        "Reservá tu sesión",
        "Creá tu cuenta y completá el pago de forma segura.",
      ],
      [
        "Nos encontramos",
        "El enlace de la videollamada estará en tu área personal cuando sea añadido.",
      ],
    ],
    faq: "Algunas preguntas, antes de empezar.",
    questions: [
      [
        "¿Cómo son las sesiones?",
        "Los encuentros son online y tienen una duración de 50 minutos. Buscá un lugar tranquilo, con privacidad y buena conexión.",
      ],
      [
        "¿Cómo reservo un horario?",
        "Elegí una fecha disponible, iniciá sesión y continuá al pago. Tu consulta se confirma cuando recibimos la aprobación del pago.",
      ],
      [
        "¿Dónde encuentro el enlace de la sesión?",
        "Ingresá a Mis consultas. Cuando Yanina añada el enlace, lo vas a encontrar junto al día y horario de tu sesión.",
      ],
    ],
    ready: "Un espacio para vos.",
    readyEm: "Un paso a la vez.",
    readyText: "Cuando sientas que es el momento, podemos empezar.",
    footer: "Psicología · Paraná, Entre Ríos",
    admin: "Acceso profesional",
    loading: "Cargando…",
    unavailable:
      "La agenda no está disponible en este momento. Intentá más tarde.",
    retry: "Volver a intentar",
    timezone: "Todos los horarios se muestran en hora de Argentina (UTC−3).",
    choose: "Elegí un horario",
    bookingNote:
      "Tu horario se guarda temporalmente mientras completás el pago. La confirmación depende del pago aprobado.",
    price: "Valor de la sesión",
    empty: "No hay horarios disponibles en los próximos 14 días.",
    selected: "Tu próxima sesión",
    paymentWait: "Verificando el pago. La consulta todavía no está confirmada.",
    paymentReview:
      "Recibimos el pago, pero esta reserva necesita revisión. Contactá a Yanina antes de asistir.",
    cancelled:
      "El pago no se completó. Podés retomarlo desde Mis consultas mientras la reserva siga vigente.",
    pending: "Pendiente de pago",
    confirmed: "Confirmada",
    completed: "Realizada",
    cancelledStatus: "Cancelada",
    expired: "Reserva vencida",
    resume: "Continuar al pago",
    join: "Entrar a la sesión",
    linkPending: "El enlace de la sesión todavía no fue añadido.",
    myEmpty: "Todavía no tenés consultas. Elegí un horario para empezar.",
    confirmEmail:
      "Revisá tu correo para confirmar la cuenta. Después, iniciá sesión para reservar.",
    notConfigured: "No disponible por el momento. Volvé a intentar más tarde.",
    forgot: "¿Olvidaste tu contraseña?",
    resetTitle: "Recuperar contraseña",
    resetSend: "Enviar enlace",
    resetSent:
      "Si existe una cuenta con ese correo, recibirás un enlace para recuperar el acceso.",
    newPassword: "Nueva contraseña",
    savePassword: "Guardar contraseña",
    resetExpired: "Abrí el enlace de recuperación que recibiste por correo.",
    statusError:
      "No pudimos verificar el pago todavía. Revisá Mis consultas o intentá otra vez.",
    slotTaken: "Ese horario acaba de reservarse. Elegí otro.",
    pendingExists:
      "Ya tenés una reserva pendiente. Continuá el pago desde Mis consultas.",
    priceUnavailable:
      "Las reservas todavía no están habilitadas. Intentá más tarde.",
    profileRequired: "No pudimos completar tu perfil. Contactá a Yanina.",
    saving: "Guardando…",
    titleField: "Título profesional",
    locationField: "Ubicación",
    currency: "Moneda de cobro",
    videoLink: "Enlace de videollamada",
    copy: "Copiar enlace",
    security: "Pago seguro con Stripe",
    back: "Volver",
    notFound: "Esta página no está disponible.",
    myIntro: "Tu espacio para consultar horarios, pagos y enlaces de sesión.",
  },
  pt: {
    about: "Sobre mim",
    approach: "Meu acompanhamento",
    how: "Como funciona",
    account: "Minhas consultas",
    logout: "Sair",
    eyebrow: "PSICOLOGIA · UM ESPAÇO PARA VOCÊ",
    heroTitle: "Voltar para si,",
    heroEm: "no seu próprio ritmo.",
    heroNote: "Um primeiro passo, sem precisar resolver tudo hoje.",
    online: "Atendimento online",
    duration: "Sessões de 50 minutos",
    language: "Espanhol e português",
    meet: "UM ENCONTRO COM VOCÊ",
    approachTitle: "Você não precisa passar",
    approachEm: "por tudo sozinha.",
    aboutLabel: "OLÁ, SOU",
    aboutTitle: "Ouvir também é",
    aboutEm: "uma forma de cuidar.",
    howLabel: "PASSO A PASSO, NO SEU RITMO",
    howTitle: "Começar pode ser simples.",
    steps: [
      [
        "Escolha um momento",
        "Consulte os horários e encontre um espaço na sua semana.",
      ],
      [
        "Reserve sua sessão",
        "Crie sua conta e conclua o pagamento com segurança.",
      ],
      [
        "Vamos nos encontrar",
        "O link da videochamada ficará na sua área pessoal quando for adicionado.",
      ],
    ],
    faq: "Algumas perguntas, antes de começar.",
    questions: [
      [
        "Como são as sessões?",
        "Os encontros são online e duram 50 minutos. Procure um lugar tranquilo, com privacidade e boa conexão.",
      ],
      [
        "Como reservo um horário?",
        "Escolha uma data disponível, entre na sua conta e continue para o pagamento. Sua consulta é confirmada quando recebemos a aprovação do pagamento.",
      ],
      [
        "Onde encontro o link da sessão?",
        "Entre em Minhas consultas. Quando Yanina adicionar o link, ele aparecerá junto ao dia e horário da sua sessão.",
      ],
    ],
    ready: "Um espaço para você.",
    readyEm: "Um passo de cada vez.",
    readyText: "Quando sentir que é o momento, podemos começar.",
    footer: "Psicologia · Paraná, Entre Ríos",
    admin: "Acesso profissional",
    loading: "Carregando…",
    unavailable: "A agenda está indisponível neste momento. Tente mais tarde.",
    retry: "Tentar novamente",
    timezone: "Todos os horários são exibidos na hora da Argentina (UTC−3).",
    choose: "Escolha um horário",
    bookingNote:
      "Seu horário fica reservado temporariamente enquanto você paga. A confirmação depende do pagamento aprovado.",
    price: "Valor da sessão",
    empty: "Não há horários disponíveis nos próximos 14 dias.",
    selected: "Sua próxima sessão",
    paymentWait:
      "Verificando o pagamento. A consulta ainda não está confirmada.",
    paymentReview:
      "Recebemos o pagamento, mas esta reserva precisa de revisão. Fale com Yanina antes de comparecer.",
    cancelled:
      "O pagamento não foi concluído. Você pode retomá-lo em Minhas consultas enquanto a reserva estiver válida.",
    pending: "Pagamento pendente",
    confirmed: "Confirmada",
    completed: "Realizada",
    cancelledStatus: "Cancelada",
    expired: "Reserva expirada",
    resume: "Continuar para pagamento",
    join: "Entrar na sessão",
    linkPending: "O link da sessão ainda não foi adicionado.",
    myEmpty: "Você ainda não tem consultas. Escolha um horário para começar.",
    confirmEmail:
      "Confira seu e-mail para confirmar a conta. Depois, entre para reservar.",
    notConfigured: "Indisponível no momento. Tente novamente mais tarde.",
    forgot: "Esqueceu sua senha?",
    resetTitle: "Recuperar senha",
    resetSend: "Enviar link",
    resetSent:
      "Se existir uma conta com esse e-mail, você receberá um link para recuperar o acesso.",
    newPassword: "Nova senha",
    savePassword: "Salvar senha",
    resetExpired: "Abra o link de recuperação recebido por e-mail.",
    statusError:
      "Ainda não conseguimos verificar o pagamento. Confira Minhas consultas ou tente novamente.",
    slotTaken: "Esse horário acabou de ser reservado. Escolha outro.",
    pendingExists:
      "Você já tem uma reserva pendente. Continue o pagamento em Minhas consultas.",
    priceUnavailable:
      "As reservas ainda não estão habilitadas. Tente mais tarde.",
    profileRequired: "Não foi possível completar seu perfil. Fale com Yanina.",
    saving: "Salvando…",
    titleField: "Título profissional",
    locationField: "Localização",
    currency: "Moeda de cobrança",
    videoLink: "Link da videochamada",
    copy: "Copiar link",
    security: "Pagamento seguro com Stripe",
    back: "Voltar",
    notFound: "Esta página não está disponível.",
    myIntro:
      "Seu espaço para consultar horários, pagamentos e links das sessões.",
  },
};
